root:         ./root
redirects:
  faq: ./faq.md
gitbook:      ">= 3.0.0"
title:        "Wechaty Documentations"
description:  "Tutorials, API, and Support."
author:       "Huan LI <zixia@zixia.net>"
links: 
  - 
    sidebar: 
      - 
        Home: "https://wechaty.github.io"
